#!/usr/bin/env bash
# query the domain  name server for the domain and sub domain


# Function to display information for a subdomain
function display_info {
    local domain="$1"
    local subdomain="$2"
    local destination
    local record_type

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do

        destination=$(dig +short "$sub.$domain" | awk 'NR==1{print}')
        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')


        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

display_info "$1" "$2"
