#!/usr/bin/env bash
#install and configure nginx server on reome server

# Update package list
sudo apt-get update

sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default'

# Create the HTML file with "Hello World!"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart Nginx
sudo service nginx restart
