#!/usr/bin/env bash
#install and configure nginx server on reome server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Create a simple "Hello World!" index.html file
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

# Define the new Nginx configuration
new_config=$(cat <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        rewrite ^ https://www.github.com/Olalekan-1 permanent;
    }
}
EOL
)

# Overwrite the default Nginx configuration file with the new configuration
echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
