#!/usr/bin/env bash
#install and configure nginx server on reome server

#install and configure nginx server on reome server

# Update package list
sudo apt-get update

sudo apt-get install -y nginx

# Check if Nginx is installed
if [ ! -f "/etc/nginx/sites-available/default" ]; then
    # Nginx is not installed, so proceed with installation

    # Change to the home directory of the user "ubuntu"
   sudo  cd /home/ubuntu

    # Execute the script for installing Nginx
    sudo ./1-1-install_nginx_web_server

else

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Use sed to add a redirection rule in the default Nginx configuration file
 sudo sed '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\trewrite ^ https:\/\/github.com\/Olalekan-1 permanent;\n\t}' /etc/nginx/sites-available/default > /tmp/default_tmp

 sudo mv /tmp/default_tmp /etc/nginx/sites-available/default
# Restart Nginx to apply the changes
sudo service nginx restart
fi
