#!/usr/bin/env bash
# handle various signal

function handle_sigterm()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

function handle_sigint()
{
	echo "Y U no love me?!"
}

function handle_sigquit()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

i=0

while (( i >= 0 ))
do
	echo "To infinity and beyond"
	sleep 2
	trap "handle_sigterm" SIGTERM
	trap "handle_sigint" SIGINT
	trap "handle_sigquit" SIGQUIT
	(( i++ ))
done
