#!/usr/bin/env bash
# Handle the sig_term

function handle_sigterm()
{
	echo "I am invincible!!!"
}

# trap "handle_sigterm" SIGTERM
i=0

while (( i >= 0 ))
do
	 trap "handle_sigterm" SIGTERM
	echo "To infinity and beyond"
	sleep 2
	(( i++ ))
done
