#!/usr/bin/env bash
# print  number occurrence of ip and status in apache log

log="./apache-access.log"

awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' "$log" | sort -nr
